CREATE DATABASE School;
USE School;
CREATE TABLE STUDENT (
    Roll_No INT PRIMARY KEY,
    Name VARCHAR(50),
    Marks INT,
    Grade CHAR(1));
INSERT INTO STUDENT (Roll_No, Name, Marks, Grade) VALUES
(1, 'Riya', 88, 'A'),
(2, 'Arjun', 72, 'B'),
(3, 'Sneha', 95, 'A'),
(4, 'Rahul', 63, 'C');
SELECT * FROM STUDENT;
ALTER TABLE STUDENT ADD Contact VARCHAR(15);
ALTER TABLE STUDENT DROP COLUMN Grade;
RENAME TABLE STUDENT TO CLASSTEN;
TRUNCATE TABLE CLASSTEN;
DROP TABLE CLASSTEN;


